# -*- coding: utf-8 -*-
"""To_do_list_pyn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4QdpRJ5T-nz5IQnfcbgfe6oEUAev4TP
"""

tasks = []

def add_task():
    task_name = input("Enter the task name: ")
    task_description = input("Enter the task description: ")
    task_due_date = input("Enter the task due date: ")
    task_status = "Incomplete"

    task = {
        "name": task_name,
        "description": task_description,
        "due_date": task_due_date,
        "status": task_status
    }

    tasks.append(task)
    print("Task added: ", task_name)

def list_tasks():
    if not tasks:
        print("No tasks in the to-do list.")
    else:
        print("To-Do List:")
        for i, task in enumerate(tasks, 1):
            print(f"{i}. Name: {task['name']}")
            print(f"   Description: {task['description']}")
            print(f"   Due Date: {task['due_date']}")
            print(f"   Status: {task['status']}")
            print()

def remove_task():
    list_tasks()
    task_index = int(input("Enter the number of the task to remove: ")) - 1

    if 0 <= task_index < len(tasks):
        removed_task = tasks.pop(task_index)
        print("Task removed: ", removed_task['name'])
    else:
        print("Invalid task number. No task removed.")

while True:
    print("\nOptions:")
    print("1. Add Task")
    print("2. List Tasks")
    print("3. Remove Task")
    print("4. Quit")
    choice = input("Enter your choice: ")

    if choice == "1":
        add_task()
    elif choice == "2":
        list_tasks()
    elif choice == "3":
        remove_task()
    elif choice == "4":
        print("Goodbye!")
        break
    else:
        print("Invalid choice. Please select a valid option.")